#!/bin/fish

set -e ARCH_INSTALL_CONFIGURATION

# WIFI
set -e ARCH_INSTALL_WIRELESS_INTERFACE
set -e ARCH_INSTALL_SSID
set -e ARCH_INSTALL_PASSWORD

# DISK
set -e ARCH_INSTALL_DISK
set -e ARCH_INSTALL_P

#
set -e ARCH_INSTALL_IP
set -e ARCH_INSTALL_HOSTNAME
set -e ARCH_INSTALL_USER
set -e ARCH_INSTALL_IDENTITY_FILE
