theme = "solarized-dark"

[icons]
name = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/mnt/evo-pro"
alias = "/evo-pro"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m} {5m} {15m}"

#[[block]]
#block = "net"
#device = "wlp31s0"
#ssid = true
#ip = true
#speed_up = false
#speed_down = false

#[[block]]
#block = "speedtest"
#bytes = true
#interval = 1800

[[block]]
block = "sound"

[[block]]
block = "temperature"
collapsed = false 
interval = 10
format = "CPU: {average}°"
chip = "k10temp-pci-00c3"

[[block]]
block = "nvidia_gpu"
#label = "GTX 1050Ti"
label = "GPU:"
show_utilization = false
show_memory = false
show_clocks = false
interval = 1
#[[block]]
#block = "temperature"
#collapsed = true
#interval = 10
#format = "GPU: {average}°"
#chip = "radeon-pci-0008"

#[[block]]
#block = "backlight"

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage}% {time}"
#device = "BAT1"

[[block]]
block = "time"
interval = 60
format = "%FT%T"
timezone = "Europe/Rome"
